#!/bin/bash

sudo cat ~/.local/bin/apk-noob/dowhat.md
printf "APK does what?\n"
read -n1 apkwhat

case $apkwhat in
  1) sudo apk update ;;
  2) sudo apk upgrade ;;
  3) echo "What to search?" && read searchable && sudo apk search -v $searchable ;;
  4) echo "Which package?" && read installpackage && sudo apk add $installpackage ;;
  5) echo "Which package?" && read checkpackage && sudo apk -e info $checkpackage ;;
  6) echo "Which package?" && read deppackacge && apk -R info $deppackacge ;;
  7) sudo apk fix ;;
  *) printf "\nNot allowed." ;;
esac
printf "\nDone, exiting..."
sleep 1
echo "Bye"
