#!/bin/bash

sudo cat ./dowhat.md
read -n1 -p "APK does what?" apkwhat

case $apkwhat in
  1) sudo apk update ;;
  2) sudo apk upgrade ;;
  3) echo "What to search?" && read searchable && sudo apk search -v $searchable ;;
  4) echo "Which package?" && read installpackage && sudo apk add $installpackage ;;
  5) echo "Which package?" && read checkpackage && sudo apk -e info $checkpackage ;;
  6) echo "Which package?" && read deppackacge && apk -R info $deppackacge ;;
  *) printf "\nNot allowed, yet. Exiting..." && sleep 1 && echo "done" ;;
esac


